### ISSUE TITLE
Question: How to add PHP?

### ISSUE THREAD

**Issue by LTepliakov** [sclorg/httpd-container#106]
When I try to add PHP to new image, based on this one I get a conflict.
PHP pulls httpd as dependency, and it conflicts with httpd24-httpd that is already present.
Any advice on how to add php into this container?

**Comment by notroj** [comment]
I'd recommend to build off one of the existing PHP images if you need a PHP-based image.

If you're using an RHSCL-based image you can install rh-php73-php which requires httpd24-httpd.
