### ISSUE TITLE
Question : Adding additional modules to the image

### ISSUE THREAD

**Issue by sakthiraam** [sclorg/httpd-container#108]
Hi, We want to use Apache as a Reverse proxy but with Form based authentication enabled. We can see the base image doesn't have the below modules.
1) LDAP
2) Session
Currently I'm adding this module manually but since our build server doesn't have connectivity to internet i'm copying the RPM file as part of the build process.

Question
1) Are we allowed to do this ?
2) How we can avoid looking up the red hat repo and ubi repo during the build process (Currently renamed the file )

Any suggestions. Thanks for your help!

**Comment by notroj** [comment]
This is fixed in current versions of the container in the registry, let us know if you see any missing.
