### ISSUE TITLE
Add apache modules

### ISSUE THREAD

**Issue by magick93** [sclorg/httpd-container#27]
What is the recommended way to add apache modules?

**Comment by notroj** [comment]
Which modules in particular?  You'd probably need to add a layer on the image, then install httpd24-httpd-devel and gcc, and whatever else is needed by the module.

**Comment by magick93** [comment]
> Which modules in particular?

In particular, mod_auth_openidc

**Comment by notroj** [comment]
OK.  This isn't something we expect to support directly in the image, we'd have to pull the toolchain, plus -devel packages, into the image.  So you'll have to do it in a layered image currently, sorry.
