### ISSUE TITLE
Not able to access my statics file

### ISSUE THREAD

**Issue by speedfl** [sclorg/httpd-container#37]
Hello,

Maybe I am doing something wrong but I am not able to access my files through openshift v3

I browsed the catalogue and got the 2.4.

My root is webstatics.mydomain.com. I am using a git repository where all the files are at the root of the project ```"./"```

I accessed my pod with:

```oc exec -it -p web-statics-1-ltlmv /bin/bash```

Then if I do an ```ls``` I can see my files. However I cannot see my files in ```/var/www```

Did I missed something?

**Comment by omron93** [comment]
> Then if I do an ls I can see my files. However I cannot see my files in /var/www

Your files are not in `/var/www`, but in `/opt/app-root/src`. And that directory is configured to be used by httpd server.

To check that server is running and serving your site run `curl localhost:8080` inside your pod.

If it's running, then problem is in routing. Have you create openshift route to be able to reach your app?


HTTPD server is running on port

**Comment by speedfl** [comment]
Hello,

Finally I went to another solution. Thanks a lot

Regards

Geoffrey MUSELLI
