### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by speedfl** [sclorg/httpd-container#38]
Hello,

I finally was able to use your s2i :)
Now I noticed that there are lot of log in console. How it is possible to disable logging?

**Comment by notroj** [comment]
You can use an httpd-pre-init/ script like:

```
$ cat httpd-pre-init/nolog.sh 
#!/bin/sh
sed -i '/CustomLog/d;/ErrorLog/d' /etc/httpd/conf/httpd.conf  /etc/httpd/conf.d/ssl.conf
sed -i '/%{SSL_PROTOCOL}x/d' /etc/httpd/conf.d/ssl.conf
```

Note the second sed since annoyingly the CustomLog line is wrapped over two lines.
