### ISSUE TITLE
Create and run OpenShift tests

### ISSUE THREAD

**Issue by pvalena** [sclorg/httpd-container#46]
IOW script `test/run-openshift`, similarly to [nginx](https://github.com/sclorg/nginx-container/blob/master/test/run-openshift).

**Comment by rdebeasi** [comment]
Does #72 resolve this issue?

**Comment by phracek** [comment]
HTTPD container is already tested agains OpenShift 3 and OpenShift 4. See tests/run-openshift-local-cluster and tests/run-openshift-remote-cluster.
