### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by zetnet** [sclorg/httpd-container#53]
I want to use sendmail or whatever mailserver with centos/httpd-24-centos7 from DockerHub.
How would be the proper way I to set this up?

**Comment by phracek** [comment]
Sorry, I don't think this was implemented. Closing this issue as it has been stale for a long time. Feel free to re-open it and even file a PR with test

**Comment by zetnet** [comment]
Stale for a long time because of no proper answer for a long time. If not sure, don't close it please. 
This issue remains unanswered and should not be closed just because it has been open for a long time. Time alone does not resolve unanswered and ignored simple questions. 

Thank you!
