### ISSUE TITLE
Wildcard routing

### ISSUE THREAD

**Issue by rdebeasi** [sclorg/httpd-container#57]
Would it be possible to add support for wildcard routing? That is, all requests would be redirected to index.html using `mod_rewrite`, and a client-side JavaScript router would pick up from there.

Many client-side application frameworks recommend this setup:
- [Vue Router](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations)
- [React Router](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server)
- [Angular Router](https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2)

It would be nice if this feature was off by default but could be enabled via an environment variable.

If you think this feature would be useful, I'd be happy to put together a PR. Thank you so much in advance for your time! :)

**Comment by notroj** [comment]
PR welcome! Doing it with FallbackResource as suggested in the first link makes sense to me, rather than the mod_rewrite solution which would not work for other configured handlers.

**Comment by rdebeasi** [comment]
I haven't been able to put together a PR for this feature, but there are a few alternatives in the meantime:

- Place the required httpd config files into your source in `./httpd-cfg`
- Build the image with Jenkins, and move the config files into place as part of your Jenkins pipeline

In the future, the [Modern Web Application builder image](https://github.com/nodeshift/centos7-s2i-web-app) may leverage this functionality. That builder [recommends](https://github.com/nodeshift/centos7-s2i-web-app/blob/master/s2i/run#L8) that production deployments use a chain build, and I imagine that httpd-container would be great for such a use case!
