### ISSUE TITLE
chown test fails

### ISSUE THREAD

**Issue by rdebeasi** [sclorg/httpd-container#76]
I get an "Operation not permitted" error when running `make test TARGET=centos7 VERSIONS=2.4`. Here's the log:

```
[....] Running command 'chown -R 1001:1001 /tmp/httpd-test-volume-nTwxxO'
chown: changing ownership of '/tmp/httpd-test-volume-nTwxxO': Operation not permitted
[FAIL] Running command 'chown -R 1001:1001 /tmp/httpd-test-volume-nTwxxO'
Stopping and removing container 0f837afd7cf328e8cf9b44aea4b0a0caf33d581b52ef68d5208531cf5ca9ec20...
0f837afd7cf328e8cf9b44aea4b0a0caf33d581b52ef68d5208531cf5ca9ec20
0f837afd7cf328e8cf9b44aea4b0a0caf33d581b52ef68d5208531cf5ca9ec20
Done.
Stopping and removing container 13d7cc5abdbcae6807414b967ad7ef074b6fe2d7ed4e695e73b8cc745841a0bb...
13d7cc5abdbcae6807414b967ad7ef074b6fe2d7ed4e695e73b8cc745841a0bb
13d7cc5abdbcae6807414b967ad7ef074b6fe2d7ed4e695e73b8cc745841a0bb
Done.
Stopping and removing container e6fdd05cddd02c46da161c96b7355a0e85be48d35ce2fc38d0c55514971c11e2...
e6fdd05cddd02c46da161c96b7355a0e85be48d35ce2fc38d0c55514971c11e2
Dumping logs for e6fdd05cddd02c46da161c96b7355a0e85be48d35ce2fc38d0c55514971c11e2
Error: Option HTTPD_LOG_TO_VOLUME is only valid for privileged runs (as UID 0).
e6fdd05cddd02c46da161c96b7355a0e85be48d35ce2fc38d0c55514971c11e2
Done.
Stopping and removing container 1abcc151edd993701586023ed7934fe627f563522638f0430c0044e5ffdc5f93...
1abcc151edd993701586023ed7934fe627f563522638f0430c0044e5ffdc5f93
1abcc151edd993701586023ed7934fe627f563522638f0430c0044e5ffdc5f93
Done.
[FAIL] Tests failed.
make: *** [common/common.mk:89: test] Error 1
```

I'm running the test script with Fedora 29 and Docker 18.09.3. I ran `dnf install go-md2man` before running the script to install the required tooling.

Any thoughts on why this might be happening? Is anyone else able to reproduce this failure?

Thank you!!

**Comment by notroj** [comment]
Which test is failing?  It is working for me.  Are you running the tests as root?  I guess the `--user 0` tests will fail otherwise...

**Comment by rdebeasi** [comment]
It looks like the tests are failing on line 109 of the test script, inside `_run_log_to_volume_test()`.

I wasn't running as root; I didn't realize that the tests needed to be run as root on the local machine. `sudo make test TARGET=centos7 VERSIONS=2.4` works for me. Would you like me to make a PR to add `sudo` before the test commands in the readme?

Thank you for looking into this!

**Comment by phracek** [comment]
Base on the latest centos7 tests 2023 everything was working properly. It was fixed by some PR. 
Closing this issue as it has been stale for a long time. Feel free to re-open it and even file a PR with test
