### ISSUE TITLE
Question about changing EnableSendfile to On?

### ISSUE THREAD

**Issue by HCHCHH** [sclorg/httpd-container#77]
After pulling the image we notice in the config file that **EnableSendfile** is set to **on** in /etc/httpd/conf/httpd.conf, whose default is **Off**.

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#enablesendfile) recommends to set **EnableSendfile** to **Off** to avoid operational problems when:
* Some platforms may have broken sendfile support that the build system did not detect, especially if the binaries were built on another box and moved to such a machine with broken sendfile support.
* On Linux the use of sendfile triggers TCP-checksum offloading bugs on certain networking cards when using IPv6.
* On Linux on Itanium, sendfile may be unable to handle files over 2GB in size.
* With a network-mounted DocumentRoot (e.g., NFS, SMB, CIFS, FUSE), the kernel may be unable to serve the network file through its own cache.

So I wonder if **EnableSendfile** should be changed back to "off" as default.

**Comment by notroj** [comment]
The container image inherits the httpd package default here, and we've been enabling sendfile by default for a while (RHEL7+).  The concerns upstream are largely historic, I haven't seen any problem reports around sendfile for a long time (decade+ probably).
