### ISSUE TITLE
Adding rsync to this container (discussion)

### ISSUE THREAD

**Issue by cdrage** [sclorg/httpd-container#78]
Hey @hhorak @notroj 

Any way possible we could add `rsync` to this container?

As part of the openshift/odo project (see https://github.com/openshift/odo/issues/1609)

We've been using rsync extensively in order to transfer files over to s2i / OpenShift cluster images.

Now, each `s2i` image (most of them, php, ruby, python, etc.) use: `s2i-base-centos7` https://github.com/sclorg/s2i-php-container/blob/master/7.2/Dockerfile#L1

Which I believe includes `rsync`.

However, httpd, uses `core`: https://github.com/sclorg/httpd-container/blob/master/2.4/Dockerfile#L1 which I believe does not.

Is there *any* way possible we could add `rsync` to the list of packages located here: https://github.com/sclorg/httpd-container/blob/master/2.4/Dockerfile#L37 ?

**Comment by pkubatrh** [comment]
A [PR](https://github.com/sclorg/s2i-base-container/pull/169) for adding rsync to the installed packages has been open against s2i-core for a long time, will revisit.

**Comment by pkubatrh** [comment]
PR for s2i-core merged

**Comment by notroj** [comment]
Thanks @pkubatrh!

**Comment by cdrage** [comment]
Awesome! Thank you @pkubatrh
