### ISSUE TITLE
RHEL7: package httpd24-mod_security is not installed

### ISSUE THREAD

**Issue by dkarnutsch** [sclorg/httpd-container#89]
The latest path (https://github.com/sclorg/httpd-container/pull/86/) breaks our build with the following message: `package httpd24-mod_security is not installed` while executing: 

```
/bin/sh -c yum install -y yum-utils &&     prepare-yum-repositories rhel-server-rhscl-7-rpms &&     INSTALL_PKGS="gettext hostname nss_wrapper bind-utils httpd24 httpd24-mod_ssl httpd24-mod_auth_mellon httpd24-mod_security" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*'
```

Any ideas?

**Comment by pkubatrh** [comment]
Hi @dkarnutsch 
The `httpd24-mod_security` rpm has been added to the httpd 2.4 SCL in RHSCL 3.3 so my best guess would be that you are trying to build the image from an old (RHSCL 3.2-based) mirror?

**Comment by dkarnutsch** [comment]
@pkubatrh thank you!
