### ISSUE TITLE
Cert problem

### ISSUE THREAD

**Issue by atgreen** [sclorg/httpd-container#93]
I host a couple of sites on the same host by running this container image along with my own certs, which are on the host and mounted into the container like so:

podman ...  -v /etc/pki/tls:/etc/pki/tls ...

This doesn't work anymore.   Running the container by hand, it exits after this...

=> sourcing 10-set-mpm.sh ...
=> sourcing 20-copy-config.sh ...
=> sourcing 40-ssl-certs.sh ...
---> Generating SSL key pair for httpd...

What's the preferred way to handle this now?

**Comment by atgreen** [comment]
I found this documentation.. https://github.com/sclorg/httpd-container/tree/master/2.4#using-own-ssl-certificates .. but placing the private key in the container seems like a bad idea.

**Comment by uhliarik** [comment]
> I host a couple of sites on the same host by running this container image along with my own certs, which are on the host and mounted into the container like so:
> 
> podman ... -v /etc/pki/tls:/etc/pki/tls ...
> 
> This doesn't work anymore. Running the container by hand, it exits after this...
> 
> => sourcing 10-set-mpm.sh ...
> => sourcing 20-copy-config.sh ...
> => sourcing 40-ssl-certs.sh ...
> ---> Generating SSL key pair for httpd...
> 
> What's the preferred way to handle this now?

Hi Anthony,
what's inside the directory (/etc/pki/tls), you are trying to mount? There has been change in default cert/key filename (mentioned here - https://github.com/sclorg/httpd-container/tree/master/2.4#default-ssl-certificates) . I guess, you have in your /etc/pki/tls files as following:
```
/etc/pki/tls/certs/localhost.crt.
/etc/pki/tls/private/localhost.key
```

Try to adjust filenames like:
```
/etc/httpd/tls/localhost.key
/etc/httpd/tls/localhost.crt
```

**Comment by atgreen** [comment]
That was it.. thank you!
